### ISSUE TITLE
How to add physical effects to glb files, make physical exports in Blender? Or the model itself does not physically add ammo.js to physics in three.js. If there is a sub-object in a concave model, how to deal with physical effects?

### ISSUE THREAD

**Issue by WREQI** [teradonburi/threejs#1]
How to add physical effects to glb files, make physical exports in Blender? Or the model itself does not physically add ammo.js to physics in three.js. If there is a sub-object in a concave model, how to deal with physical effects?
![image](https://user-images.githubusercontent.com/35467304/64059907-9e050300-cbf7-11e9-9d7a-02c991871dbc.png)

**Comment by teradonburi** [comment]
Firstly, I'm not sure about .glb and not professional game programmer.
Therefore, I can't correct advice to you.
.glb can load as .glsl with Three.js GLTFloader.
https://threejs.org/docs/#examples/en/loaders/GLTFLoader
I think you would deal with that .glb model without physics object attachment in blender.
(difficult to separate physics object from render object after loading)
Use render debugging object like box wireframe is better.

**Comment by WREQI** [comment]
@teradonburi Thank you for your reply, I saw your demo, the physics engine did not use the Worker?Use Worker faster

**Comment by teradonburi** [comment]
ammo.js is built with emscripten(WebAssemly Compiler)
So, fastly computing in browser.
https://emscripten.org/ 
The original physics engine is bullet(C/C++ language).
https://github.com/bulletphysics/bullet3
WebWorker is good idea, but synchronize problem to rendering.
